name: Check typos

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  check-typos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get latest configuration
        run: |
          wget https://raw.githubusercontent.com/julelang/jule/refs/heads/master/_typos.toml

      - name: Run spellcheck
        uses: crate-ci/typos@master
